/*****************************************************************************/
/* Project name:  Kate plugin for Russell prover integration                 */
/* File Name:     plugin_kate_russell_LatexToUnicode.cpp                     */
/* Description:   translator from latex to unicode                           */
/* Copyright:     (c) 2011 Dmitri Vlasov                                     */
/* Author:        Dmitri Yurievich Vlasov, Novosibirsk, Russia               */
/* Email:         vlasov at academ.org                                       */
/* Based on:      Copyright (c) 2010 Sven Kreiss <sk@svenkreiss.com>,        */ 
/* Based on:      Copyright (c) 2010 Kyle Cranmer <kyle.cranmer@nyu.edu>     */
/* URL:           http://mathdevlanguage.sourceforge.net                     */
/* Modified by:                                                              */
/* License:       GNU General Public License Version 3                       */
/*****************************************************************************/

#ifndef PLUGIN_KATE_RUSSELL_LATEX_TO_UNICODE_CPP_
#define PLUGIN_KATE_RUSSELL_LATEX_TO_UNICODE_CPP_

#include "plugin_kate_russell.hpp"

namespace plugin {
namespace kate {
namespace russell {

	/****************************
	 *	Public members
	 ****************************/

	LatexToUnicode :: LatexToUnicode (const QString& latexString) :
	latexString_ (latexString),
	unicodeString_ (latexString) {
	}
	LatexToUnicode :: ~ LatexToUnicode() {
	}

	const QString& 
	LatexToUnicode :: translate() 
	{
		for (int i = 1; i < FONT_COUNT; ++ i) {
			translateFont (fonts_ [i]);
		}
		for (int i = 0; i < replacementsCount_; ++ i) {
			const Pair_ pair = replacements_ [i];
			unicodeString_.replace (pair.source_, pair.image_);
		}
		for (int i = 0; i < combiningMarksCount_; ++ i) {
			const Pair_ pair = combiningMarks_ [i];
			unicodeString_.replace (pair.source_, pair.image_);
		}
		for (int i = 0; i < subSuperScriptsCount_; ++ i) {
			const Pair_ pair = subSuperScripts_ [i];
			unicodeString_.replace (pair.source_, pair.image_);
		}
		return unicodeString_;
	}
	
	/****************************
	 *	Private members
	 ****************************/

	void 
	LatexToUnicode :: translateFont (const Font_& font)
	{
		QString insertion;
		int start = 0;
		while (true) {
			int key = unicodeString_.indexOf (font.keyword_, start);
			if (key == -1) {
				return;
			}
			int length = font.keyword_.length();
			unicodeString_.remove (key, length);
			int end = unicodeString_.indexOf (QLatin1Char('}'), start);
			for (int i = start; i < end;) {
				insertion = translateFont (unicodeString_[i], font);
				unicodeString_.remove (i, 1);
				unicodeString_.insert (i, insertion);
				end += insertion.length() - 1;
				i += insertion.length();
			}
			unicodeString_.remove (end, 1);
			start = end;
		}
	}
	QString
	LatexToUnicode :: translateFont (const QChar ch, const Font_& font)
	{
		if (ch.isUpper()) {
			const char code = (ch.toLatin1() - 65);
			const uint newCode [1] =  { code + font.upperShift_ };
			return QString :: fromUcs4 (newCode, 1);
		}
		if (ch.isLower()) {
			const char code = (ch.toLatin1() - 97);
			const uint newCode [1] =  { code + font.lowerShift_ };
			return QString :: fromUcs4 (newCode, 1);
		}
		return QString (ch);
	}

	LatexToUnicode :: Pair_ :: Pair_ (const char* source, const char* image) :
	source_ (QString :: fromUtf8 (source)),
	image_ (QString :: fromUtf8 (image)) {
	}
	LatexToUnicode :: Exception_ :: Exception_ (const char ch, const char* image) :
	char_ (ch),
	image_ (QString :: fromUtf8 (image)) {
	}
	LatexToUnicode :: Font_ :: Font_ 
	(
		const QString& keyword,
		const uint lowerShift, 
		const uint upperShift/*,
		const int exceptionCount, 
		const Exception_ exceptions[]*/
	) :
	keyword_ (keyword),
	lowerShift_ (lowerShift),
	upperShift_ (upperShift)//,
	//exceptionCount_ (exceptionCount),
	//exceptions_ (exceptions) 
	{
	}


	/************************************
	 *	Static private attributes
	 ************************************/

	const LatexToUnicode :: Font_ 
		LatexToUnicode :: fonts_ [FONT_COUNT] = 
	{ 	
		Font_ (QStringLiteral("\\rm{"), 119834, 119808),      // "\u1D41A", "\u1D400"
		Font_ (QStringLiteral("\\it{"), 119886, 119860),      // "\u1D44E", "\u1D434"
		Font_ (QStringLiteral("\\bf{"), 119834, 119808),      // "\u1D41A", "\u1D400"
		Font_ (QStringLiteral("\\tt{"), 120458, 120432)       // "\u1D68A", "\u1D670"
	};

	const int LatexToUnicode :: replacementsCount_ = 707;
	const int LatexToUnicode :: combiningMarksCount_ = 6;
	const int LatexToUnicode :: subSuperScriptsCount_ = 55;

	const LatexToUnicode :: Pair_ 
		LatexToUnicode :: replacements_ [] = 
	{ 
		Pair_ ("\\textfractionsolidus", "\u2044"),
		Pair_ ("\\leftrightsquigarrow", "\u21AD"),
		Pair_ ("\\textpertenthousand", "\u2031"),
		Pair_ ("\\blacktriangleright", "\u25B8"),
		Pair_ ("\\blacktriangledown", "\u25BE"),
		Pair_ ("\\blacktriangleleft", "\u25C2"),
		Pair_ ("\\twoheadrightarrow", "\u21A0"),
		Pair_ ("\\leftrightharpoons", "\u21CB"),
		Pair_ ("\\rightleftharpoons", "\u21CC"),
		Pair_ ("\\textreferencemark", "\u203B"),
		Pair_ ("\\circlearrowright", "\u21BB"),
		Pair_ ("\\rightrightarrows", "\u21C9"),
		Pair_ ("\\vartriangleright", "\u22B3"),
		Pair_ ("\\textordmasculine", "\u00BA"),
		Pair_ ("\\textvisiblespace", "\u2423"),
		Pair_ ("\\twoheadleftarrow", "\u219E"),
		Pair_ ("\\downharpoonright", "\u21C2"),
		Pair_ ("\\ntrianglerighteq", "\u22ED"),
		Pair_ ("\\rightharpoondown", "\u21C1"),
		Pair_ ("\\textperthousand", "\u2030"),
		Pair_ ("\\leftrightarrows", "\u21C6"),
		Pair_ ("\\textmusicalnote", "\u266A"),
		Pair_ ("\\nleftrightarrow", "\u21AE"),
		Pair_ ("\\rightleftarrows", "\u21C4"),
		Pair_ ("\\bigtriangledown", "\u25BD"),
		Pair_ ("\\textordfeminine", "\u00AA"),
		Pair_ ("\\ntrianglelefteq", "\u22EC"),
		Pair_ ("\\rightthreetimes", "\u22CC"),
		Pair_ ("\\trianglerighteq", "\u22B5"),
		Pair_ ("\\vartriangleleft", "\u22B2"),
		Pair_ ("\\rightsquigarrow", "\u21DD"),
		Pair_ ("\\downharpoonleft", "\u21C3"),
		Pair_ ("\\curvearrowright", "\u21B7"),
		Pair_ ("\\circlearrowleft", "\u21BA"),
		Pair_ ("\\leftharpoondown", "\u21BD"),
		Pair_ ("\\nLeftrightarrow", "\u21CE"),
		Pair_ ("\\curvearrowleft", "\u21B6"),
		Pair_ ("\\guilsinglright", "\u203A"),
		Pair_ ("\\leftthreetimes", "\u22CB"),
		Pair_ ("\\leftrightarrow", "\u2194"),
		Pair_ ("\\rightharpoonup", "\u21C0"),
		Pair_ ("\\guillemotright", "\u00BB"),
		Pair_ ("\\downdownarrows", "\u21CA"),
		Pair_ ("\\hookrightarrow", "\u21AA"),
		Pair_ ("\\hspace{0.25em}", "\u2005"),
		Pair_ ("\\dashrightarrow", "\u21E2"),
		Pair_ ("\\leftleftarrows", "\u21C7"),
		Pair_ ("\\trianglelefteq", "\u22B4"),
		Pair_ ("\\ntriangleright", "\u22EB"),
		Pair_ ("\\doublebarwedge", "\u2306"),
		Pair_ ("\\upharpoonright", "\u21BE"),
		Pair_ ("\\rightarrowtail", "\u21A3"),
		Pair_ ("\\looparrowright", "\u21AC"),
		Pair_ ("\\Leftrightarrow", "\u21D4"),
		Pair_ ("\\sphericalangle", "\u2222"),
		Pair_ ("\\divideontimes", "\u22C7"),
		Pair_ ("\\measuredangle", "\u2221"),
		Pair_ ("\\blacktriangle", "\u25B4"),
		Pair_ ("\\ntriangleleft", "\u22EA"),
		Pair_ ("\\mathchar\"1356\"", "\u2041"),
		Pair_ ("\\texttrademark", "\u2122"),
		Pair_ ("\\mathchar\"2208\"", "\u2316"),
		Pair_ ("\\triangleright", "\u25B9"),
		Pair_ ("\\leftarrowtail", "\u21A2"),
		Pair_ ("\\guilsinglleft", "\u2039"),
		Pair_ ("\\upharpoonleft", "\u21BF"),
		Pair_ ("\\mathbb{gamma}", "\u213D"),
		Pair_ ("\\fallingdotseq", "\u2252"),
		Pair_ ("\\dashleftarrow", "\u21E0"),
		Pair_ ("\\looparrowleft", "\u21AB"),
		Pair_ ("\\textbrokenbar", "\u00A6"),
		Pair_ ("\\hookleftarrow", "\u21A9"),
		Pair_ ("\\smallsetminus", "\uFE68"),
		Pair_ ("\\guillemotleft", "\u00AB"),
		Pair_ ("\\leftharpoonup", "\u21BC"),
		Pair_ ("\\mathbb{Gamma}", "\u213E"),
		Pair_ ("\\bigtriangleup", "\u25B3"),
		Pair_ ("\\textcircledP", "\u2117"),
		Pair_ ("\\risingdotseq", "\u2253"),
		Pair_ ("\\triangleleft", "\u25C3"),
		Pair_ ("\\mathsterling", "\u00A3"),
		Pair_ ("\\textcurrency", "\u00A4"),
		Pair_ ("\\triangledown", "\u25BF"),
		Pair_ ("\\blacklozenge", "\uE80B"),
		Pair_ ("\\sfrac{5}{6}", "\u215A"),
		Pair_ ("\\preccurlyeq", "\u227C"),
		Pair_ ("\\Rrightarrow", "\u21DB"),
		Pair_ ("\\circledcirc", "\u229A"),
		Pair_ ("\\nRightarrow", "\u21CF"),
		Pair_ ("\\sfrac{3}{8}", "\u215C"),
		Pair_ ("\\sfrac{1}{3}", "\u2153"),
		Pair_ ("\\sfrac{2}{5}", "\u2156"),
		Pair_ ("\\vartriangle", "\u25B5"),
		Pair_ ("\\Updownarrow", "\u21D5"),
		Pair_ ("\\nrightarrow", "\u219B"),
		Pair_ ("\\sfrac{1}{2}", "\u00BD"),
		Pair_ ("\\sfrac{3}{5}", "\u2157"),
		Pair_ ("\\succcurlyeq", "\u227D"),
		Pair_ ("\\sfrac{4}{5}", "\u2158"),
		Pair_ ("\\diamondsuit", "\u2666"),
		Pair_ ("\\hphantom{0}", "\u2007"),
		Pair_ ("\\sfrac{1}{6}", "\u2159"),
		Pair_ ("\\curlyeqsucc", "\u22DF"),
		Pair_ ("\\blacksquare", "\u25AA"),
		Pair_ ("\\hphantom{,}", "\u2008"),
		Pair_ ("\\curlyeqprec", "\u22DE"),
		Pair_ ("\\sfrac{1}{8}", "\u215B"),
		Pair_ ("\\sfrac{7}{8}", "\u215E"),
		Pair_ ("\\sfrac{1}{5}", "\u2155"),
		Pair_ ("\\sfrac{2}{3}", "\u2154"),
		Pair_ ("\\updownarrow", "\u2195"),
		Pair_ ("\\backepsilon", "\u220D"),
		Pair_ ("\\circleddash", "\u229D"),
		Pair_ ("\\eqslantless", "\u22DC"),
		Pair_ ("\\sfrac{3}{4}", "\u00BE"),
		Pair_ ("\\sfrac{5}{8}", "\u215D"),
		Pair_ ("\\hspace{1pt}", "\u200A"),
		Pair_ ("\\sfrac{1}{4}", "\u00BC"),
		Pair_ ("\\mathbb{Pi}", "\u213F"),
		Pair_ ("\\mathcal{M}", "\u2133"),
		Pair_ ("\\nsupseteqq", "\u2289"),
		Pair_ ("\\mathcal{B}", "\u212C"),
		Pair_ ("\\textrecipe", "\u211E"),
		Pair_ ("\\nsubseteqq", "\u2288"),
		Pair_ ("\\subsetneqq", "\u228A"),
		Pair_ ("\\mathcal{I}", "\u2111"),
		Pair_ ("\\upuparrows", "\u21C8"),
		Pair_ ("\\mathcal{e}", "\u212F"),
		Pair_ ("\\mathcal{L}", "\u2112"),
		Pair_ ("\\nleftarrow", "\u219A"),
		Pair_ ("\\mathcal{H}", "\u210B"),
		Pair_ ("\\mathcal{E}", "\u2130"),
		Pair_ ("\\eqslantgtr", "\u22DD"),
		Pair_ ("\\curlywedge", "\u22CF"),
		Pair_ ("\\varepsilon", "\u03B5"),
		Pair_ ("\\supsetneqq", "\u228B"),
		Pair_ ("\\rightarrow", "\u2192"),
		Pair_ ("\\mathcal{R}", "\u211B"),
		Pair_ ("\\sqsubseteq", "\u2291"),
		Pair_ ("\\mathcal{g}", "\u210A"),
		Pair_ ("\\sqsupseteq", "\u2292"),
		Pair_ ("\\complement", "\u2201"),
		Pair_ ("\\Rightarrow", "\u21D2"),
		Pair_ ("\\gtreqqless", "\u22DB"),
		Pair_ ("\\lesseqqgtr", "\u22DA"),
		Pair_ ("\\circledast", "\u229B"),
		Pair_ ("\\nLeftarrow", "\u21CD"),
		Pair_ ("\\Lleftarrow", "\u21DA"),
		Pair_ ("\\Leftarrow", "\u21D0"),
		Pair_ ("\\gvertneqq", "\u2269"),
		Pair_ ("\\mathbb{C}", "\u2102"),
		Pair_ ("\\supsetneq", "\u228B"),
		Pair_ ("\\leftarrow", "\u2190"),
		Pair_ ("\\nleqslant", "\u2270"),
		Pair_ ("\\mathbb{Q}", "\u211A"),
		Pair_ ("\\mathbb{Z}", "\u2124"),
		Pair_ ("\\llbracket", "\u301A"),
		Pair_ ("\\mathbb{H}", "\u210D"),
		Pair_ ("\\spadesuit", "\u2660"),
		Pair_ ("\\mathit{o}", "\u2134"),
		Pair_ ("\\mathbb{P}", "\u2119"),
		Pair_ ("\\rrbracket", "\u301B"),
		Pair_ ("\\supseteqq", "\u2287"),
		Pair_ ("\\copyright", "\u00A9"),
		Pair_ ("\\textsc{k}", "\u0138"),
		Pair_ ("\\gtreqless", "\u22DB"),
		Pair_ ("\\mathbb{j}", "\u2149"),
		Pair_ ("\\pitchfork", "\u22D4"),
		Pair_ ("\\estimated", "\u212E"),
		Pair_ ("\\ngeqslant", "\u2271"),
		Pair_ ("\\mathbb{e}", "\u2147"),
		Pair_ ("\\therefore", "\u2234"),
		Pair_ ("\\triangleq", "\u225C"),
		Pair_ ("\\varpropto", "\u221D"),
		Pair_ ("\\subsetneq", "\u228A"),
		Pair_ ("\\heartsuit", "\u2665"),
		Pair_ ("\\mathbb{d}", "\u2146"),
		Pair_ ("\\lvertneqq", "\u2268"),
		Pair_ ("\\checkmark", "\u2713"),
		Pair_ ("\\nparallel", "\u2226"),
		Pair_ ("\\mathbb{R}", "\u211D"),
		Pair_ ("\\lesseqgtr", "\u22DA"),
		Pair_ ("\\downarrow", "\u2193"),
		Pair_ ("\\mathbb{D}", "\u2145"),
		Pair_ ("\\mathbb{i}", "\u2148"),
		Pair_ ("\\backsimeq", "\u22CD"),
		Pair_ ("\\mathbb{N}", "\u2115"),
		Pair_ ("\\Downarrow", "\u21D3"),
		Pair_ ("\\subseteqq", "\u2286"),
		Pair_ ("\\setminus", "\u2216"),
		Pair_ ("\\succnsim", "\u22E9"),
		Pair_ ("\\doteqdot", "\u2251"),
		Pair_ ("\\clubsuit", "\u2663"),
		Pair_ ("\\emptyset", "\u2205"),
		Pair_ ("\\sqsupset", "\u2290"),
		Pair_ ("\\fbox{~~}", "\u25AD"),
		Pair_ ("\\curlyvee", "\u22CE"),
		Pair_ ("\\varkappa", "\u03F0"),
		Pair_ ("\\llcorner", "\u231E"),
		Pair_ ("\\varsigma", "\u03C2"),
		Pair_ ("\\approxeq", "\u224A"),
		Pair_ ("\\backcong", "\u224C"),
		Pair_ ("\\supseteq", "\u2287"),
		Pair_ ("\\circledS", "\u24C8"),
		Pair_ ("\\circledR", "\u00AE"),
		Pair_ ("\\textcent", "\u00A2"),
		Pair_ ("\\urcorner", "\u231D"),
		Pair_ ("\\lrcorner", "\u231F"),
		Pair_ ("\\boxminus", "\u229F"),
		Pair_ ("\\texteuro", "\u20AC"),
		Pair_ ("\\vartheta", "\u03D1"),
		Pair_ ("\\barwedge", "\u22BC"),
		Pair_ ("\\ding{86}", "\u2736"),
		Pair_ ("\\sqsubset", "\u228F"),
		Pair_ ("\\subseteq", "\u2286"),
		Pair_ ("\\intercal", "\u22BA"),
		Pair_ ("\\ding{73}", "\u2606"),
		Pair_ ("\\ulcorner", "\u231C"),
		Pair_ ("\\recorder", "\u2315"),
		Pair_ ("\\precnsim", "\u22E8"),
		Pair_ ("\\parallel", "\u2225"),
		Pair_ ("\\boxtimes", "\u22A0"),
		Pair_ ("\\ding{55}", "\u2717"),
		Pair_ ("\\multimap", "\u22B8"),
		Pair_ ("\\maltese", "\u2720"),
		Pair_ ("\\nearrow", "\u2197"),
		Pair_ ("\\swarrow", "\u2199"),
		Pair_ ("\\lozenge", "\u25CA"),
		Pair_ ("\\sqrt[3]", "\u221B"),
		Pair_ ("\\succsim", "\u227F"),
		Pair_ ("\\tilde{}", "~"),
		Pair_ ("\\lessgtr", "\u2276"),
		Pair_ ("\\Upsilon", "\u03D2"),
		Pair_ ("\\Cdprime", "\u042A"),
		Pair_ ("\\gtrless", "\u2277"),
		Pair_ ("\\backsim", "\u223D"),
		Pair_ ("\\nexists", "\u2204"),
		Pair_ ("\\dotplus", "\u2214"),
		Pair_ ("\\searrow", "\u2198"),
		Pair_ ("\\lessdot", "\u22D6"),
		Pair_ ("\\boxplus", "\u229E"),
		Pair_ ("\\upsilon", "\u03C5"),
		Pair_ ("\\epsilon", "\u03B5"),
		Pair_ ("\\diamond", "\u22C4"),
		Pair_ ("\\bigstar", "\u2605"),
		Pair_ ("\\ddagger", "\u2021"),
		Pair_ ("\\cdprime", "\u044A"),
		Pair_ ("\\Uparrow", "\u21D1"),
		Pair_ ("\\sqrt[4]", "\u221C"),
		Pair_ ("\\between", "\u226C"),
		Pair_ ("\\sqangle", "\u221F"),
		Pair_ ("\\digamma", "\u03DC"),
		Pair_ ("\\uparrow", "\u2191"),
		Pair_ ("\\nwarrow", "\u2196"),
		Pair_ ("\\precsim", "\u227E"),
		Pair_ ("\\breve{}", "\u02D8"),
		Pair_ ("\\because", "\u2235"),
		Pair_ ("\\bigcirc", "\u25EF"),
		Pair_ ("\\acute{}", "\u00B4"),
		Pair_ ("\\grave{}", "\u0060"),
		Pair_ ("\\check{}", "\u02C7"),
		Pair_ ("\\lesssim", "\u2272"),
		Pair_ ("\\partial", "\u2202"),
		Pair_ ("\\natural", "\u266E"),
		Pair_ ("\\supset", "\u2283"),
		Pair_ ("\\hstrok", "\u0127"),
		Pair_ ("\\Tstrok", "\u0166"),
		Pair_ ("\\coprod", "\u2210"),
		Pair_ ("\\models", "\u22A7"),
		Pair_ ("\\otimes", "\u2297"),
		Pair_ ("\\degree", "\u00B0"),
		Pair_ ("\\gtrdot", "\u22D7"),
		Pair_ ("\\preceq", "\u227C"),
		Pair_ ("\\Lambda", "\u039B"),
		Pair_ ("\\lambda", "\u03BB"),
		Pair_ ("\\cprime", "\u044C"),
		Pair_ ("\\varrho", "\u03F1"),
		Pair_ ("\\Bumpeq", "\u224E"),
		Pair_ ("\\hybull", "\u2043"),
		Pair_ ("\\lmidot", "\u0140"),
		Pair_ ("\\nvdash", "\u22AC"),
		Pair_ ("\\lbrace", "{"),
		Pair_ ("\\bullet", "\u2022"),
		Pair_ ("\\varphi", "\u03D5"),
		Pair_ ("\\bumpeq", "\u224F"),
		Pair_ ("\\ddot{}", "\u00A8"),
		Pair_ ("\\Lmidot", "\u013F"),
		Pair_ ("\\Cprime", "\u042C"),
		Pair_ ("\\female", "\u2640"),
		Pair_ ("\\rtimes", "\u22CA"),
		Pair_ ("\\gtrsim", "\u2273"),
		Pair_ ("\\mapsto", "\u21A6"),
		Pair_ ("\\daleth", "\u2138"),
		Pair_ ("\\square", "\u25A0"),
		Pair_ ("\\nVDash", "\u22AF"),
		Pair_ ("\\rangle", "\u3009"),
		Pair_ ("\\tstrok", "\u0167"),
		Pair_ ("\\oslash", "\u2298"),
		Pair_ ("\\ltimes", "\u22C9"),
		Pair_ ("\\lfloor", "\u230A"),
		Pair_ ("\\marker", "\u25AE"),
		Pair_ ("\\Subset", "\u22D0"),
		Pair_ ("\\Vvdash", "\u22AA"),
		Pair_ ("\\propto", "\u221D"),
		Pair_ ("\\dlcrop", "\u230D"),
		Pair_ ("\\Hstrok", "\u0126"),
		Pair_ ("\\forall", "\u2200"),
		Pair_ ("\\nVdash", "\u22AE"),
		Pair_ ("\\Supset", "\u22D1"),
		Pair_ ("\\langle", "\u3008"),
		Pair_ ("\\ominus", "\u2296"),
		Pair_ ("\\rfloor", "\u230B"),
		Pair_ ("\\circeq", "\u2257"),
		Pair_ ("\\eqcirc", "\u2256"),
		Pair_ ("\\drcrop", "\u230C"),
		Pair_ ("\\veebar", "\u22BB"),
		Pair_ ("\\ulcrop", "\u230F"),
		Pair_ ("\\nvDash", "\u22AD"),
		Pair_ ("\\urcrop", "\u230E"),
		Pair_ ("\\exists", "\u2203"),
		Pair_ ("\\approx", "\u2248"),
		Pair_ ("\\dagger", "\u2020"),
		Pair_ ("\\boxdot", "\u22A1"),
		Pair_ ("\\succeq", "\u227D"),
		Pair_ ("\\bowtie", "\u22C8"),
		Pair_ ("\\subset", "\u2282"),
		Pair_ ("\\Sigma", "\u03A3"),
		Pair_ ("\\Omega", "\u03A9"),
		Pair_ ("\\nabla", "\u2207"),
		Pair_ ("\\colon", ":"),
		Pair_ ("\\boxHu", "\u2567"),
		Pair_ ("\\boxHd", "\u2564"),
		Pair_ ("\\aleph", "\u2135"),
		Pair_ ("\\gnsim", "\u22E7"),
		Pair_ ("\\boxHU", "\u2569"),
		Pair_ ("\\boxHD", "\u2566"),
		Pair_ ("\\equiv", "\u2261"),
		Pair_ ("\\lneqq", "\u2268"),
		Pair_ ("\\alpha", "\u03B1"),
		Pair_ ("\\amalg", "\u2210"),
		Pair_ ("\\boxhU", "\u2568"),
		Pair_ ("\\boxhD", "\u2565"),
		Pair_ ("\\uplus", "\u228E"),
		Pair_ ("\\boxhu", "\u2534"),
		Pair_ ("\\kappa", "\u03BA"),
		Pair_ ("\\sigma", "\u03C3"),
		Pair_ ("\\boxDL", "\u2557"),
		Pair_ ("\\Theta", "\u0398"),
		Pair_ ("\\Vdash", "\u22A9"),
		Pair_ ("\\boxDR", "\u2554"),
		Pair_ ("\\boxDl", "\u2556"),
		Pair_ ("\\sqcap", "\u2293"),
		Pair_ ("\\boxDr", "\u2553"),
		Pair_ ("\\bar{}", "\u00AF"),
		Pair_ ("\\dashv", "\u22A3"),
		Pair_ ("\\vDash", "\u22A8"),
		Pair_ ("\\boxdl", "\u2510"),
		Pair_ ("\\boxVl", "\u2562"),
		Pair_ ("\\boxVh", "\u256B"),
		Pair_ ("\\boxVr", "\u255F"),
		Pair_ ("\\boxdr", "\u250C"),
		Pair_ ("\\boxdL", "\u2555"),
		Pair_ ("\\boxVL", "\u2563"),
		Pair_ ("\\boxVH", "\u256C"),
		Pair_ ("\\boxVR", "\u2560"),
		Pair_ ("\\boxdR", "\u2552"),
		Pair_ ("\\theta", "\u03B8"),
		Pair_ ("\\lhblk", "\u2584"),
		Pair_ ("\\uhblk", "\u2580"),
		Pair_ ("\\ldotp", "."),
		Pair_ ("\\ldots", "\u2026"),
		Pair_ ("\\boxvL", "\u2561"),
		Pair_ ("\\boxvH", "\u256A"),
		Pair_ ("\\boxvR", "\u255E"),
		Pair_ ("\\boxvl", "\u2524"),
		Pair_ ("\\boxvh", "\u253C"),
		Pair_ ("\\boxvr", "\u251C"),
		Pair_ ("\\Delta", "\u0394"),
		Pair_ ("\\boxUR", "\u255A"),
		Pair_ ("\\boxUL", "\u255D"),
		Pair_ ("\\oplus", "\u2295"),
		Pair_ ("\\boxUr", "\u2559"),
		Pair_ ("\\boxUl", "\u255C"),
		Pair_ ("\\doteq", "\u2250"),
		Pair_ ("\\happy", "\u32E1"),
		Pair_ ("\\varpi", "\u03D6"),
		Pair_ ("\\boxur", "\u2514"),
		Pair_ ("\\smile", "\u263A"),
		Pair_ ("\\boxul", "\u2518"),
		Pair_ ("\\simeq", "\u2243"),
		Pair_ ("\\boxuR", "\u2558"),
		Pair_ ("\\boxuL", "\u255B"),
		Pair_ ("\\boxhd", "\u252C"),
		Pair_ ("\\gimel", "\u2137"),
		Pair_ ("\\Gamma", "\u0393"),
		Pair_ ("\\lnsim", "\u22E6"),
		Pair_ ("\\sqcup", "\u2294"),
		Pair_ ("\\omega", "\u03C9"),
		Pair_ ("\\sharp", "\u266F"),
		Pair_ ("\\times", "\u00D7"),
		Pair_ ("\\block", "\u2588"),
		Pair_ ("\\hat{}", "^"),
		Pair_ ("\\wedge", "\u2227"),
		Pair_ ("\\vdash", "\u22A2"),
		Pair_ ("\\angle", "\u2220"),
		Pair_ ("\\infty", "\u221E"),
		Pair_ ("\\gamma", "\u03B3"),
		Pair_ ("\\asymp", "\u224D"),
		Pair_ ("\\rceil", "\u2309"),
		Pair_ ("\\dot{}", "\u02D9"),
		Pair_ ("\\lceil", "\u2308"),
		Pair_ ("\\delta", "\u03B4"),
		Pair_ ("\\gneqq", "\u2269"),
		Pair_ ("\\frown", "\u2322"),
		Pair_ ("\\phone", "\u260E"),
		Pair_ ("\\vdots", "\u22EE"),
		Pair_ ("\\k{i}", "\u012F"),
		Pair_ ("\\`{I}", "\u00CC"),
		Pair_ ("\\perp", "\u22A5"),
		Pair_ ("\"{o}", "\u00F6"),
		Pair_ ("\\={I}", "\u012A"),
		Pair_ ("\\`{a}", "\u00E0"),
		Pair_ ("\\v{T}", "\u0164"),
		Pair_ ("\\surd", "\u221A"),
		Pair_ ("\\H{O}", "\u0150"),
		Pair_ ("\\vert", "|"),
		Pair_ ("\\k{I}", "\u012E"),
		Pair_ ("\"{y}", "\u00FF"),
		Pair_ ("\"{O}", "\u00D6"),
		Pair_ ("\\\'{Y}", "\u00DD"),
		Pair_ ("\\u{u}", "\u045E"),
		Pair_ ("\\u{G}", "\u011E"),
		Pair_ ("\\.{E}", "\u0116"),
		Pair_ ("\\.{z}", "\u017C"),
		Pair_ ("\\^{s}", "\u015D"),
		Pair_ ("\\v{t}", "\u0165"),
		Pair_ ("\\prec", "\u227A"),
		Pair_ ("\\H{o}", "\u0151"),
		Pair_ ("\\mldr", "\u2026"),
		Pair_ ("\\\'{y}", "\u00FD"),
		Pair_ ("\\cong", "\u2245"),
		Pair_ ("\\.{e}", "\u0117"),
		Pair_ ("\\\'{L}", "\u0139"),
		Pair_ ("\\star", "*"),
		Pair_ ("\\.{Z}", "\u017B"),
		Pair_ ("\\r{u}", "\u016F"),
		Pair_ ("\\\'{e}", "\u00E9"),
		Pair_ ("\\geqq", "\u2267"),
		Pair_ ("\\cdot", "\u22C5"),
		Pair_ ("\\`{U}", "\u00D9"),
		Pair_ ("\\\'{l}", "\u013A"),
		Pair_ ("\\^{J}", "\u0134"),
		Pair_ ("\\v{L}", "\u013D"),
		Pair_ ("\\c{s}", "\u015F"),
		Pair_ ("\\\'{s}", "\u015B"),
		Pair_ ("\\~{A}", "\u00C3"),
		Pair_ ("\\Vert", "\u2016"),
		Pair_ ("\\k{e}", "\u0119"),
		Pair_ ("\\lnot", "\u00AC"),
		Pair_ ("\\\'{z}", "\u017A"),
		Pair_ ("\\leqq", "\u2266"),
		Pair_ ("\\beta", "\u03B2"),
		Pair_ ("\\beth", "\u2136"),
		Pair_ ("\\\'{E}", "\u00C9"),
		Pair_ ("\\~{n}", "\u00F1"),
		Pair_ ("\\u{i}", "\u0439"),
		Pair_ ("\\c{S}", "\u015E"),
		Pair_ ("\\c{N}", "\u0145"),
		Pair_ ("\\H{u}", "\u0171"),
		Pair_ ("\\v{n}", "\u0148"),
		Pair_ ("\\\'{S}", "\u015A"),
		Pair_ ("\\={U}", "\u016A"),
		Pair_ ("\\~{O}", "\u00D5"),
		Pair_ ("\\^{I}", "\u00CE"),
		Pair_ ("\\\'{Z}", "\u0179"),
		Pair_ ("\\v{E}", "\u011A"),
		Pair_ ("\\\'{R}", "\u0154"),
		Pair_ ("\\H{U}", "\u0170"),
		Pair_ ("\\v{N}", "\u0147"),
		Pair_ ("\\prod", "\u220F"),
		Pair_ ("\\^{W}", "\u0174"),
		Pair_ ("\\v{s}", "\u0161"),
		Pair_ ("\\\"{U}", "\u00DC"),
		Pair_ ("\\c{n}", "\u0146"),
		Pair_ ("\\^{e}", "\u00EA"),
		Pair_ ("\\k{U}", "\u0172"),
		Pair_ ("\\c{R}", "\u0156"),
		Pair_ ("\\\'{A}", "\u00C1"),
		Pair_ ("\\~{o}", "\u00F5"),
		Pair_ ("\\v{e}", "\u011B"),
		Pair_ ("\\^{w}", "\u0175"),
		Pair_ ("\\v{S}", "\u0160"),
		Pair_ ("\\u{A}", "\u0102"),
		Pair_ ("\\circ", "\u2218"),
		Pair_ ("\"{u}", "\u00FC"),
		Pair_ ("\\^{E}", "\u00CA"),
		Pair_ ("\\flat", "\u266D"),
		Pair_ ("\\v{z}", "\u017E"),
		Pair_ ("\\^{S}", "\u015C"),
		Pair_ ("\\^{a}", "\u00E2"),
		Pair_ ("\\`{O}", "\u00D2"),
		Pair_ ("\\={u}", "\u016B"),
		Pair_ ("\\oint", "\u222E"),
		Pair_ ("\\c{K}", "\u0136"),
		Pair_ ("\\k{u}", "\u0173"),
		Pair_ ("\\not<", "\u226E"),
		Pair_ ("\\not>", "\u226F"),
		Pair_ ("\\`{o}", "\u00F2"),
		Pair_ ("\"{I}", "\u00CF"),
		Pair_ ("\\v{D}", "\u010E"),
		Pair_ ("\\^{H}", "\u0124"),
		Pair_ ("\\.{G}", "\u0120"),
		Pair_ ("\\^{A}", "\u00C2"),
		Pair_ ("\\^{o}", "\u00F4"),
		Pair_ ("\\not=", "\u2260"),
		Pair_ ("\\`{u}", "\u00F9"),
		Pair_ ("\\v{c}", "\u010D"),
		Pair_ ("\\c{k}", "\u0137"),
		Pair_ ("\\^{h}", "\u0125"),
		Pair_ ("\\.{g}", "\u0121"),
		Pair_ ("\\\'{N}", "\u0143"),
		Pair_ ("\\odot", "\u2299"),
		Pair_ ("\\`{e}", "\u044D"),
		Pair_ ("\\c{T}", "\u0162"),
		Pair_ ("\\v{d}", "\u010F"),
		Pair_ ("\"{e}", "\u0451"),
		Pair_ ("\\\'{I}", "\u00CD"),
		Pair_ ("\\v{R}", "\u0158"),
		Pair_ ("\\^{u}", "\u00FB"),
		Pair_ ("\\k{a}", "\u0105"),
		Pair_ ("\\nldr", "\u2025"),
		Pair_ ("\\^{O}", "\u00D4"),
		Pair_ ("\\`{A}", "\u00C0"),
		Pair_ ("\\\'{n}", "\u0144"),
		Pair_ ("\\~{N}", "\u00D1"),
		Pair_ ("\\nmid", "\u2224"),
		Pair_ ("\\.{C}", "\u010A"),
		Pair_ ("\\zeta", "\u03B6"),
		Pair_ ("\\~{u}", "\u0169"),
		Pair_ ("\\`{E}", "\u042D"),
		Pair_ ("\\~{a}", "\u00E3"),
		Pair_ ("\\c{t}", "\u0163"),
		Pair_ ("\\={o}", "\u014D"),
		Pair_ ("\\v{r}", "\u0159"),
		Pair_ ("\\={A}", "\u0100"),
		Pair_ ("\\.{c}", "\u010B"),
		Pair_ ("\\r{U}", "\u016E"),
		Pair_ ("\\~{U}", "\u0168"),
		Pair_ ("\\k{A}", "\u0104"),
		Pair_ ("\"{a}", "\u00E4"),
		Pair_ ("\\u{U}", "\u040E"),
		Pair_ ("\\iota", "\u03B9"),
		Pair_ ("\\={O}", "\u014C"),
		Pair_ ("\\c{C}", "\u00C7"),
		Pair_ ("\\gneq", "\u2269"),
		Pair_ ("\\\'{c}", "\u0107"),
		Pair_ ("\\boxH", "\u2550"),
		Pair_ ("\\hbar", "\u210F"),
		Pair_ ("\"{A}", "\u00C4"),
		Pair_ ("\\boxv", "\u2502"),
		Pair_ ("\\boxh", "\u2500"),
		Pair_ ("\\male", "\u2642"),
		Pair_ ("\\\'{u}", "\u00FA"),
		Pair_ ("\\sqrt", "\u221A"),
		Pair_ ("\\succ", "\u227B"),
		Pair_ ("\\^{Y}", "\u0176"),
		Pair_ ("\\^{g}", "\u011D"),
		Pair_ ("\\c{c}", "\u00E7"),
		Pair_ ("\\\'{C}", "\u0106"),
		Pair_ ("\\^{C}", "\u0108"),
		Pair_ ("\\v{l}", "\u013E"),
		Pair_ ("\\u{a}", "\u0103"),
		Pair_ ("\\v{Z}", "\u017D"),
		Pair_ ("\\\'{o}", "\u00F3"),
		Pair_ ("\\c{G}", "\u0122"),
		Pair_ ("\\^{G}", "\u011C"),
		Pair_ ("\\v{C}", "\u010C"),
		Pair_ ("\\lneq", "\u2268"),
		Pair_ ("\"\{E}", "\u0401"),
		Pair_ ("\\={a}", "\u0101"),
		Pair_ ("\\^{y}", "\u0177"),
		Pair_ ("\\^{U}", "\u00DB"),
		Pair_ ("\\c{l}", "\u013C"),
		Pair_ ("\\^{c}", "\u0109"),
		Pair_ ("\\\'{a}", "\u00E1"),
		Pair_ ("\\={E}", "\u0112"),
		Pair_ ("\\boxV", "\u2551"),
		Pair_ ("\\u{g}", "\u011F"),
		Pair_ ("\\\'{O}", "\u00D3"),
		Pair_ ("\\\'{g}", "\u01F5"),
		Pair_ ("\\u{I}", "\u0419"),
		Pair_ ("\\c{L}", "\u013B"),
		Pair_ ("\\k{E}", "\u0118"),
		Pair_ ("\\.{I}", "\u0130"),
		Pair_ ("\\~{I}", "\u0128"),
		Pair_ ("\\quad", "\u2003"),
		Pair_ ("\\c{r}", "\u0157"),
		Pair_ ("\\\'{r}", "\u0155"),
		Pair_ ("\"{Y}", "\u0178"),
		Pair_ ("\\={e}", "\u0113"),
		Pair_ ("\\\'{U}", "\u00DA"),
		Pair_ ("\\leq", "\u2264"),
		Pair_ ("\\Cup", "\u22D3"),
		Pair_ ("\\Psi", "\u03A8"),
		Pair_ ("\\dzh", "\u045F"),
		Pair_ ("\\H{}", "\u02DD"),
		Pair_ ("\\k{}", "\u02DB"),
		Pair_ ("\\={}", "\u203E"),
		Pair_ ("\\cup", "\u222A"),
		Pair_ ("\\geq", "\u2265"),
		Pair_ ("\\mho", "\u2127"),
		Pair_ ("\\Dzh", "\u040F"),
		Pair_ ("\\cap", "\u2229"),
		Pair_ ("\\bot", "\u22A5"),
		Pair_ ("\\psi", "\u03C8"),
		Pair_ ("\\chi", "\u03C7"),
		Pair_ ("\\c{}", "\u00B8"),
		Pair_ ("\\Phi", "\u03A6"),
		Pair_ ("\\ast", "*"),
		Pair_ ("\\ell", "\u2113"),
		Pair_ ("\\top", "\u22A4"),
		Pair_ ("\\lll", "\u22D8"),
		Pair_ ("\\tau", "\u03C4"),
		Pair_ ("\\Cap", "\u22D2"),
		Pair_ ("\\sad", "\u2639"),
		Pair_ ("\\iff", "\u21D4"),
		Pair_ ("\\eta", "\u03B7"),
		Pair_ ("\\eth", "\u00F0"),
		Pair_ ("\\d{}", "\u0323"),
		Pair_ ("\\rho", "\u03C1"),
		Pair_ ("\\div", "\u00F7"),
		Pair_ ("\\phi", "\u03C6"),
		Pair_ ("\\Rsh", "\u21B1"),
		Pair_ ("\\vee", "\u2228"),
		Pair_ ("\\b{}", "\u02CD"),
		Pair_ ("\\t{}", "\u0361"),
		Pair_ ("\\int", "\u222B"),
		Pair_ ("\\sim", "\u223C"),
		Pair_ ("\\r{}", "\u02DA"),
		Pair_ ("\\Lsh", "\u21B0"),
		Pair_ ("\\yen", "\u00A5"),
		Pair_ ("\\ggg", "\u22D9"),
		Pair_ ("\\mid", "\u2223"),
		Pair_ ("\\sum", "\u2211"),
		Pair_ ("\\Dz", "\u0405"),
		Pair_ ("\\Re", "\u211C"),
		Pair_ ("\\oe", "\u0153"),
		Pair_ ("\\DH", "\u00D0"),
		Pair_ ("\\ll", "\u226A"),
		Pair_ ("\\=e", "\u0454"),
		Pair_ ("\\ng", "\u014B"),
		Pair_ ("\\\'G", "\u0403"),
		Pair_ ("\\wr", "\u2240"),
		Pair_ ("\\wp", "\u2118"),
		Pair_ ("\\=I", "\u0406"),
		Pair_ ("\\:)", "\u263A"),
		Pair_ ("\\:(", "\u2639"),
		Pair_ ("\\AE", "\u00C6"),
		Pair_ ("\\AA", "\u00C5"),
		Pair_ ("\\ss", "\u00DF"),
		Pair_ ("\\dz", "\u0455"),
		Pair_ ("\\ae", "\u00E6"),
		Pair_ ("\\aa", "\u00E5"),
		Pair_ ("\\th", "\u00FE"),
		Pair_ ("\\to", "\u2192"),
		Pair_ ("\\Pi", "\u03A0"),
		Pair_ ("\\mp", "\u2213"),
		Pair_ ("\\Im", "\u2111"),
		Pair_ ("\\pm", "\u00B1"),
		Pair_ ("\\pi", "\u03C0"),
		Pair_ ("\"I", "\u0407"),
		Pair_ ("\\\'C", "\u040B"),
		Pair_ ("\\in", "\u2208"),
		Pair_ ("\\\'k", "\u045C"),
		Pair_ ("\\\'c", "\u045B"),
		Pair_ ("\\\'g", "\u0453"),
		Pair_ ("\\ni", "\u220B"),
		Pair_ ("\\TH", "\u00DE"),
		Pair_ ("\\Xi", "\u039E"),
		Pair_ ("\\nu", "\u03BD"),
		Pair_ ("\\NG", "\u014A"),
		Pair_ ("\\:G", "\u32E1"),
		Pair_ ("\\xi", "\u03BE"),
		Pair_ ("\\\'K", "\u040C"),
		Pair_ ("\\OE", "\u0152"),
		Pair_ ("\\gg", "\u226B"),
		Pair_ ("\\DJ", "\u0110"),
		Pair_ ("\\=E", "\u0404"),
		Pair_ ("\\mu", "\u03BC"),
		Pair_ ("\\dj", "\u0111"),
		Pair_ ("\\:", "\u2004"),
		Pair_ ("\\;", "\u2002"),
		Pair_ ("\\&", "&"),
		Pair_ ("\\$", "$"),
		Pair_ ("\\%", "%"),
		Pair_ ("\\#", "#"),
		Pair_ ("\\,", "\u2009"),
		Pair_ ("\\-", "\u00AD"),
		Pair_ ("\\S", "\u00A7"),
		Pair_ ("\\P", "\u00B6"),
		Pair_ ("\\O", "\u00D8"),
		Pair_ ("\\L", "\u0141"),
		Pair_ ("\\}", "}"),
		Pair_ ("\\o", "\u00F8"),
		Pair_ ("\\l", "\u0142"),
		Pair_ ("\\h", "\u210E"),
		Pair_ ("\\i", "\u2139"),
	};
	const LatexToUnicode :: Pair_ 
		LatexToUnicode :: combiningMarks_ [] = 
	{
		Pair_ ("\\tilde", "\u0303"),
		Pair_ ("\\grave", "\u0300"),
		Pair_ ("\\dot", "\u0307"),
		Pair_ ("\\acute", "\u0301"),
		Pair_ ("\\doubleunderline", "\u0333"),
		Pair_ ("\\ddot", "\u0308"), 
	};
 	const LatexToUnicode :: Pair_ 
		LatexToUnicode :: subSuperScripts_ [] = 
	{
		Pair_ ("^3", "\u00B3"),
		Pair_ ("^4", "\u2074"),
		Pair_ ("^5", "\u2075"),
		Pair_ ("_\u03C1", "\u1D68"),
		Pair_ ("_\u03C7", "\u1D6A"),
		Pair_ ("_\u03C6", "\u1D69"),
		Pair_ ("^7", "\u2077"),
		Pair_ ("^8", "\u2078"),
		Pair_ ("^9", "\u2079"),
		Pair_ ("^i", "\u2071"),
		Pair_ ("^=", "\u207C"),
		Pair_ ("_x", "\u2093"),
		Pair_ ("^0", "\u2070"),
		Pair_ ("_v", "\u1D65"),
		Pair_ ("_u", "\u1D64"),
		Pair_ ("_t", "\u209C"),
		Pair_ ("_s", "\u209B"),
		Pair_ ("_r", "\u1D63"),
		Pair_ ("^6", "\u2076"),
		Pair_ ("_p", "\u209A"),
		Pair_ ("_o", "\u2092"),
		Pair_ ("_n", "\u2099"),
		Pair_ ("_m", "\u2098"),
		Pair_ ("_l", "\u2097"),
		Pair_ ("_k", "\u2096"),
		Pair_ ("_j", "\u2C7C"),
		Pair_ ("_i", "\u1D62"),
		Pair_ ("_h", "\u2095"),
		Pair_ ("_e", "\u2091"),
		Pair_ ("_a", "\u2090"),
		Pair_ ("^-", "\u207B"),
		Pair_ ("^)", "\u207E"),
		Pair_ ("^n", "\u207F"),
		Pair_ ("_\u03B2", "\u1D66"),
		Pair_ ("_\u03B3", "\u1D67"),
		Pair_ ("^*", "*"),
		Pair_ ("^+", "\u207A"),
		Pair_ ("_=", "\u208C"),
		Pair_ ("_9", "\u2089"),
		Pair_ ("_8", "\u2088"),
		Pair_ ("_7", "\u2087"),
		Pair_ ("_6", "\u2086"),
		Pair_ ("_5", "\u2085"),
		Pair_ ("_4", "\u2084"),
		Pair_ ("_3", "\u2083"),
		Pair_ ("_2", "\u2082"),
		Pair_ ("_1", "\u2081"),
		Pair_ ("_0", "\u2080"),
		Pair_ ("^1", "\u00B9"),
		Pair_ ("_-", "\u208B"),
		Pair_ ("^(", "\u207D"),
		Pair_ ("_+", "\u208A"),
		Pair_ ("_)", "\u208E"),
		Pair_ ("_(", "\u208D"),
		Pair_ ("^2", "\u00B2"), 
	};
}
}
}

#endif /* PLUGIN_KATE_RUSSELL_LATEX_TO_UNICODE_CPP_ */

